name: Artifact CI

on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: sudo apt-get install libcurl4
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew linkReleaseExecutableMingwX64 linkReleaseExecutableLinuxX64
      - name: Release to gh
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/**/*.exe
            build/**/*.kexe